directories:
  output: release
  buildResources: build
appId: com.frqliner.app
productName: Frqliner
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.png
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: public/icon.png
  category: public.app-category.music
linux:
  target:
    - AppImage
  icon: public/icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerLanguages:
    - ko_KR
    - en_US
  language: '1042'
electronVersion: 40.6.1
